### PR TITLE
Closes #68. Fixing Vidrian Borders.

### LINKED ISSUE #68: Vidrian Borders
The borders for Vidrian in the Lost Omens World Guide are wrong. A very large chunk of their northern lands is cut off. The borders need to be redrawn from either the Inner Sea World Guide (1e book) or Lost Omens: The Mwangi Expanse (page 275).

### PR DESCRIPTION
**Pull request by VestOfHolding**
Closes #68

### CODE REVIEW

**Comment by VestOfHolding** [comment]
That diff picture doesn't help at all unfortunately, lol. I used the borders established in Lost Omens: The Mwangi Expanse.

**Comment by manuel-hegner** [comment]
Yeah. The diff is only useful for the other shape of the whole layer.

On small thing: border should not cross islands unless those are really split. Otherwise we will have a gray line on this island in the resulting map.

**Comment by VestOfHolding** [comment]
> Yeah. The diff is only useful for the other shape of the whole layer.
> 
> On small thing: border should not cross islands unless those are really split. Otherwise we will have a gray line on this island in the resulting map.

My bad for missing this comment. Just fixed.

**Comment by VestOfHolding** [comment]
Closing this PR as this work was merged into master through another commit.

**Pull request closed without merging**
